runtime: python27
api_version: 1
threadsafe: yes
service: pwa-starter-kit

libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.5.2"

default_expiration: "1m"
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic

handlers:
- url: /css
  static_dir: css
  secure: always
- url: /images
  static_dir: images
  secure: always
- url: /.*
  script: main.app
  secure: always
